Repository CyBear-Jinni/cbj_smart-device, pull requests merged in 2020-10, with the labels that each got.

#35 Adding Linkedin icon
  README.md
Labels: Hacktoberfest, Hacktoberfest 2020

#42 Hacktober
  README.md
Labels: Hacktoberfest, Hacktoberfest 2020

#58 Feature/56 change readme logo url
  README.md
Labels: Hacktoberfest, Hacktoberfest 2020, hacktoberfest-accepted

#60 move parts in readme
  README.md
Labels: hacktoberfest, hacktoberfest 2020, hacktoberfest-accepted

#70 Fixes issue #66
  scripts/bashScripts/dartSdkDownload.sh
Labels: hacktoberfest, hacktoberfest 2020, hacktoberfest-accepted

#71 Change License badge in README.md
  README.md
Labels: hacktoberfest, hacktoberfest 2020, hacktoberfest-accepted

#78 Change the Open Source badge
  README.md
Labels: hacktoberfest, hacktoberfest 2020, hacktoberfest-accepted

#83 Add badge for Snapcraft
  README.md
Labels: hacktoberfest, hacktoberfest 2020, hacktoberfest-accepted

#93 Update README.md
  README.md
Labels: hacktoberfest, hacktoberfest 2020, hacktoberfest-accepted
